### ISSUE TITLE
 Server Error: 500 at  rest/widget/variation/WBVar...

### ISSUE THREAD

**Issue by wormbasehelp** [WormBase/website#5042]
*Submitted from the feedback form on the WormBase website.*

<p>Server Error: 500 at <a href="http://www.wormbase.org/rest/widget/variation/WBVar02125754/molecular_details">rest/widget/variation/WBVar02125754/molecular_details</a></p><p></p><p>Error Message:<br> Caught exception in WormBase::Web::Controller::REST->widget "Neither wild type sequence [CTT] nor reverse complment matches DNA [gaa] at /var/lib/jenkins/jobs/staging_build/workspace/lib/WormBase/API/Object/Variation.pm line 1729." </p>

**Reported by:** Nikh********* (nikh*****************)
**Submitted from:** <a target="_blank" href="http://www.wormbase.org//tools/support">/tools/support</a>
**Browser:** Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Safari/537.36

**Comment by sibyl229** [comment]
Looks like the case of the sequence isn't correctly handled. I will fix it.

**Comment by sibyl229** [comment]
Hi @tuli I'm looking into several tickets on displaying variation sequence in molecular details widget on Variation page. The issue seems to be whether the web code should do a **reverse** complement or just a complement on the variation sequence. Since this part of code hasn't changed for a long time (since 2013), I wonder if there's a recent data change that might caused the problem, and whether it's intentional. 

I imagine the data change that might get the web code confuse would probably involve the representation of strand, start and stop coordinates, or the sequence of the mutation in either GFF or ACeDB. Do you recall anything like that? Any thoughts on this will be appreciated. Thank you!

Making a note for myself of where the code is: https://github.com/WormBase/website/blob/staging/lib/WormBase/API/Object/Variation.pm#L1575-L1783

**Comment by sibyl229** [comment]
Hi @tuli @rankishore @tharris I think the broken molecular details widget on variation page has been fixed on staging. Below is a list of variation that were reported to be broken. They are all deletions located on the negative strand. Could someone please check if the sequence shown is correct? Thank you very much. 

vs101	http://staging.wormbase.org/search/variation/vs101
ok1449	http://staging.wormbase.org/search/variation/ok1449
ok1251	http://staging.wormbase.org/search/variation/ok1251
gm407	http://staging.wormbase.org/search/variation/gm407
gm344	http://staging.wormbase.org/search/variation/gm344
h2875	http://staging.wormbase.org/search/variation/h2875

**Comment by chris-grove** [comment]
@sibyl229  It looks like they're all fixed, and referencing the correct sequences (and deleted sequences). Closing.

**Comment by sibyl229** [comment]
Thanks a lot @chris-grove !

**Comment by rankishore** [comment]
@sibyl229: From #5057, it seems that this issue still remains, see the variation ok91, it's molecular details are broken on both live and staging.
